-- setup/create_staging_external_table.sql — SUPERSEDED, kept only as a
-- pointer for anyone who finds this path from an old bookmark/doc.
--
-- This used to be a one-time, manually-run Hive-external-table DDL. It
-- assumed a Hive Metastore-backed catalog that was never actually part of
-- the stack (Trino here only has the `gates` catalog, backed by Nessie —
-- see deployment/trino/etc/catalog/gates.properties), so the DDL below
-- would never have worked as written, and nothing ever populated the
-- `_gx_validation_status` column it filtered on.
--
-- The real staging table is now a native Iceberg table in the same
-- `gates` catalog dbt already uses (gates.staging.{dataset}_raw),
-- created and populated idempotently by common/trino_loader.py
-- (ensure_staging_table / load_validated_batch), called from the
-- promote_to_staging Airflow task in orchestration/airflow_dag.py right
-- after trigger_gx_validation passes. No manual DDL step, no second
-- catalog/metastore. See transformation/dbt_project/models/sources.yml for
-- the dbt-facing description of the resulting table.
